---

- name: Copy files to ec2 instance
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Extract files
  shell: |
    cd /home/ubuntu
    tar xvzf artifact.tar.gz -C .
    

- name: Start backend
  shell: |
    cd /home/ubuntu
    npm install
    npm run build
    cd dist  
    pm2 start main.js