---

- name: Remove node_modules
  file:
    path: /root/project/backend/node_modules
    state: absent

- name: Remove dist
  file:
    path: /root/project/backend/dist
    state: absent

- name: Copy backend files
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: Install dependencies
  shell: |
    cd /home/ubuntu/backend
    npm install
    
- name: Build backend
  shell: |
    cd /home/ubuntu/backend
    npm run build
    npm run prestart:prod

- name: Start PM2
  shell: |
    cd /home/ubuntu/backend 
    pm2 start npm --name backend -- start